from django.urls import path,re_path
from ..views import *

app_name = 'src'
urlpatterns = [
    path('dashboard', profile.index, name='dashboard'),
    path('organizations', organizations.index, name='organizations'),
    path('ajax-organization-list', organizations.ajaxOrganizationList, name='ajax-organization-list'),
    path('ajax-organization-lists', organizations.ajaxOrganizationLists, name='ajax-organization-lists'),
    path('add-organization', organizations.addOrganization, name='add-organization'),
    path('save-organization', organizations.saveOrganization, name='save-organization'),
    path('edit-organization', organizations.editOrganization, name='edit-organization'),
    path('update-organization', organizations.updateOrganization, name='update-organization'),
    path('get-organization-record', organizations.getOrganizationRecord, name='get-organization-record'),
    path('update-organization-status', organizations.updateOrganizationStatus, name='update-organization-status'),
    path('add-department', organizations.addDepartment, name='add-department'),
    path('save-department', organizations.saveDepartment, name='save-department'),
    path('edit-department', organizations.editDepartment, name='edit-department'),
    path('update-department', organizations.updateDepartment, name='update-department'),
    path('update-department-status', organizations.updateDepartmentStatus, name='update-department-status'),
    path('export-organizations-to-xlsx/<str:columns>', organizations.exportToXlsx, name='export-organizations-to-xlsx'),
    path('export-organizations-to-pdf/<str:columns>', organizations.exportToPDF, name="export-organizations-to-pdf"),
    
    path('roles', roleManagement.index, name='roles'),
    path('ajax-role-list', roleManagement.ajaxRoleList, name='ajax-role-list'),
    path('ajax-role-lists', roleManagement.ajaxRoleLists, name='ajax-role-lists'),
    path('add-role', roleManagement.addRole, name='add-role'),
    path('add-role-permission', roleManagement.addRolePermission, name='add-role-permission'),
    path('update-role-status', roleManagement.updateRoleStatus, name='update-role-status'),
    path('edit-role', roleManagement.editRole, name='edit-role'),

    path('users', userManagement.index, name='users'),
    path('send-email', userManagement.sendEmail, name='send-email'),
    path('ajax-operational-users-list', userManagement.ajaxOperationalUsersList, name='ajax-operational-users-list'),
    path('ajax-non-operational-users-list', userManagement.ajaxNonOperationalUsersList, name='ajax-non-operational-users-list'),
    path('ajax-employee-users-list', userManagement.ajaxEmployeeUsersList, name='ajax-employee-users-list'),
    path('add-user-basic-detail', userManagement.addUserBasicDetail, name='add-user-basic-detail'),
    path('edit-user-basic-detail', userManagement.editUserBasicDetail, name='edit-user-basic-detail'),
    path('add-user-offical-detail', userManagement.addUserOfficalDetail, name='add-user-offical-detail'),
    path('edit-user-offical-detail', userManagement.editUserOfficalDetail, name='edit-user-offical-detail'),
    path('add-user-product-detail', userManagement.addUserProductDetail, name='add-user-product-detail'),
    path('update-user-variant-price', userManagement.updateUserVariantPrice, name='update-user-variant-price'),
    path('edit-user-product-detail', userManagement.editUserProductDetail, name='edit-user-product-detail'),
    path('add-user-document-detail', userManagement.addUserDocumentDetail, name='add-user-document-detail'),
    path('update-user-status', userManagement.updateUserStatus, name='update-user-status'),
    path('export-operational-user-to-xlsx/<str:columns>', userManagement.exportOperationalUserToXlsx, name='export-operational-user-to-xlsx'),
    path('export-operational-user-to-pdf/<str:columns>', userManagement.exportOperationalUserToPdf, name='export-operational-user-to-pdf'),
    path('export-non-operational-user-to-xlsx/<str:columns>', userManagement.exportNonOperationalUserToXlsx, name='export-non-operational-user-to-xlsx'),
    path('export-non-operational-user-to-pdf/<str:columns>', userManagement.exportNonOperationalUserToPdf, name='export-non-operational-user-to-pdf'),
    path('export-employee-to-xlsx/<str:columns>', userManagement.exportEmployeeToXlsx, name='export-employee-to-xlsx'),
    path('export-employee-to-pdf/<str:columns>', userManagement.exportEmployeeToPdf, name='export-employee-to-pdf'),
    path('import-product-variant', userManagement.importProductVariant, name='import-product-variant'),

    path('add-employee-basic-detail', userManagement.addEmployeeBasicDetail, name='add-employee-basic-detail'),
    path('add-employee-official-detail', userManagement.addEmployeeOfficalDetail, name='add-employee-official-detail'),
    path('add-employee-attendance-detail', userManagement.addEmployeeAttendanceDetail, name='add-employee-attendance-detail'),
    path('add-employee-document-detail', userManagement.addEmployeeDocumentDetail, name='add-employee-document-detail'),

    path('edit-employee-basic-detail/<int:employee_id>', userManagement.editEmployeeBasicDetail, name='edit-employee-basic-detail'),
    path('edit-employee-official-detail/<int:employee_id>', userManagement.editEmployeeOfficalDetail, name='edit-employee-official-detail'),
    path('edit-employee-attendance-detail/<int:employee_id>', userManagement.editEmployeeAttendanceDetail, name='edit-employee-attendance-detail'),
    path('get-user-map', userManagement.getUserMap, name='get-user-map'),
    path('edit-employee-document-detail/<int:employee_id>', userManagement.editEmployeeDocumentDetail, name='edit-employee-document-detail'),

    path('user-short-details/<int:user_id>', userManagement.userShortDetail, name='user-short-details'),
    path('user-details/<int:user_id>', userManagement.userDetail, name='user-details'),
    path('employee-short-details/<int:employee_id>', userManagement.employeeShortDetail, name='employee-short-details'),
    path('employee-details/<int:employee_id>', userManagement.employeeDetail, name='employee-details'),

    path('get-state-options/<int:country_id>', ajax.stateOption, name='get-state-options'),
    path('get-city-options/<int:state_id>', ajax.cityOption, name='get-city-options'),
    path('get-options-list', ajax.getOptionsList, name='get-options-list'),
    path('edit-role/<int:role_id>', roleManagement.editRole, name='edit-role'),
    path('role-details/<int:role_id>', roleManagement.roleDetails, name='role-details'),

    path('update-favorite', ajax.updateFavorite, name='update-favorite'),
    path('get-add-role-permission/<int:role_id>', roleManagement.getAddRolePermission, name='get-add-role-permission'),
    path('get-org-department-options/<int:organization_id>', roleManagement.orgDepartmentOption, name='get-org-department-options'),
    path('get-org-role-options/<int:organization_id>', roleManagement.orgRoleOption, name='get-org-role-options'),
    path('get-department-role-options/<int:department_id>', roleManagement.departmentRoleOption, name='get-department-role-options'),
    path('get-grouped-town-options', userManagement.getGroupedTownOptions, name='get-grouped-town-options'),
    path('get-reporting-user-options/<int:role_id>', userManagement.getReportingUserOptions, name='get-reporting-user-options'),
    
    path('products', products.index, name='products'),
    path('ajax-product-list', products.ajaxProductList, name='ajax-product-list'),
    # path('ajax-product-lists', products.ajaxProductLists, name='ajax-product-lists'),
    path('add-product', products.addProduct, name='add-product'),
    path('save-product', products.saveProduct, name='save-product'),
    path('edit-product/<int:product_id>', products.editProduct, name='edit-product'),
    path('update-product-status', products.updateProductStatus, name='update-product-status'),
    path('get-product-variants/<int:product_id>', products.getProductVariants, name='get-product-variants'),
    path('ajax-product-variant-lists/<int:product_id>', products.ajaxProductVariantLists, name='ajax-product-variant-lists'),
    path('edit-product-variant/<int:product_variant_id>', products.editProductVariant, name='edit-product-variant'),
    path('add-product-variant/<int:product_id>', products.addProductVariant, name='add-product-variant'),
    path('product-unit-details/<int:unit_id>', products.productUnitDetails, name='product-unit-details'),
    path('update-product-variant-status', products.updateProductVariantStatus, name='update-product-variant-status'),


    path('schemes', scheme.index, name='schemes'),
    path('ajax-scheme-list', scheme.ajaxSchemeList, name='ajax-scheme-list'),
    path('add-scheme', scheme.addScheme, name='add-scheme'),

]